# Feature Scaling Techniques

A comparison of standard, min-max, and robust scaling on synthetic and real-valued features.

In [1]:
# Feature scaling techniques

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler

In [2]:
from numpy.random import default_rng

rng = default_rng(0)

rng.random(10)

array([0.63696169, 0.26978671, 0.04097352, 0.01652764, 0.81327024,
       0.91275558, 0.60663578, 0.72949656, 0.54362499, 0.93507242])

In [3]:
rng.random(10)*6-3

array([ 1.89512132, -2.983569  ,  2.14442566, -2.79848655,  1.37793268,
       -1.94606628,  2.17907353,  0.24876732, -1.20172866, -0.46387667])

In [4]:
df = pd.DataFrame({
    "Col_1" : rng.random(10)*6-3,
    "Col_2" : rng.random(10)*2500-500,
    "Col_3" : rng.random(10)*2,
})

In [5]:
df.head()

      Col_1        Col_2     Col_3
0 -2.830082  1221.116826  1.143060
1 -2.254300   472.303560  0.643739
2  1.023746  -162.258737  1.188600
3  0.883137  1303.720850  0.675822
4  0.692311   813.385806  0.783238

In [6]:
# Standard scaling: (x_i - mean) / standard deviation

In [7]:
columns = df.columns
features = df

scaler = StandardScaler().fit(features)
features = scaler.transform(features)


print(features.max())
print(features.min())

scaled_features = pd.DataFrame(features, columns = columns)

scaled_features.head()

1.63391864103759
-1.8179948751662325

      Col_1     Col_2     Col_3
0 -1.817995  0.587066  0.341038
1 -1.500811 -0.627511 -0.671625
2  0.304981 -1.656772  0.433398
3  0.227523  0.721050 -0.606557
4  0.122402 -0.074275 -0.388710

In [8]:
columns = df.columns
features = df

scaler = MinMaxScaler().fit(features)
features = scaler.transform(features)


print(features.max())
print(features.min())

scaled_features = pd.DataFrame(features, columns = columns)

scaled_features.head()

1.0
0.0

      Col_1     Col_2     Col_3
0  0.000000  0.692599  0.604662
1  0.099045  0.317699  0.295009
2  0.662928  0.000000  0.632904
3  0.638741  0.733956  0.314906
4  0.605915  0.488465  0.381520

In [9]:
columns = df.columns
features = df

scaler = RobustScaler().fit(features)
features = scaler.transform(features)


print(features.max())
print(features.min())

scaled_features = pd.DataFrame(features, columns = columns)

scaled_features.head()

1.4503485584950733
-2.5831959770519295

      Col_1     Col_2     Col_3
0 -2.583196  0.525964  0.310100
1 -2.183694 -0.335605 -0.550545
2  0.090755 -1.065719  0.388594
3 -0.006806  0.621006 -0.495244
4 -0.139210  0.056837 -0.310100

In [10]:
# Haberman dataset
cols = ["Age", "Year", "Nodes", "Class"]

dataset = pd.read_csv('Desktop/haberman+s+survival/haberman.data', names = cols, header=None, sep=",")

dataset

     Age  Year  Nodes  Class
0     30    64      1      1
1     30    62      3      1
2     30    65      0      1
3     31    59      2      1
4     31    65      4      1
..   ...   ...    ...    ...
301   75    62      1      1
302   76    67      0      1
303   77    65      3      1
304   78    65      1      2
305   83    58      2      2

[306 rows x 4 columns]

In [11]:
# Robust scaling
columns = dataset.drop(columns=["Class"]).columns
features = dataset.drop(columns=["Class"])

scaler = RobustScaler().fit(features)
features = scaler.transform(features)


print(features.max())
print(features.min())

scaled_features = pd.DataFrame(features, columns = columns)

scaled_features.head()

12.75
-1.3134328358208955

        Age      Year  Nodes
0 -1.313433  0.173913   0.00
1 -1.313433 -0.173913   0.50
2 -1.313433  0.347826  -0.25
3 -1.253731 -0.695652   0.25
4 -1.253731  0.347826   0.75

In [12]:
# Min-max scaling
columns = dataset.drop(columns=["Class"]).columns
features = dataset.drop(columns=["Class"])

scaler = MinMaxScaler().fit(features)
features = scaler.transform(features)


print(features.max())
print(features.min())

scaled_features = pd.DataFrame(features, columns = columns)

scaled_features.head()

1.0
0.0

        Age      Year     Nodes
0  0.000000  0.545455  0.019231
1  0.000000  0.363636  0.057692
2  0.000000  0.636364  0.000000
3  0.018868  0.090909  0.038462
4  0.018868  0.636364  0.076923

In [13]:
# Standard scaling
columns = dataset.drop(columns=["Class"]).columns
features = dataset.drop(columns=["Class"])

scaler = StandardScaler().fit(features)
features = scaler.transform(features)


print(features.max())
print(features.min())

scaled_features = pd.DataFrame(features, columns = columns)

scaled_features.head()

6.683554009258708
-2.08214014240774

        Age      Year     Nodes
0 -2.082140  0.353584 -0.421592
1 -2.082140 -0.262921 -0.142959
2 -2.082140  0.661837 -0.560909
3 -1.989426 -1.187680 -0.282275
4 -1.989426  0.661837 -0.003642